Don't require Statement class in SqlQuery hooks
In some situations the class is not accessible, which causes crashes
like
Caused by: java.lang.NoClassDefFoundError: java/sql/Statement
    at com.appland.appmap.process.hooks.SqlQuery.prepareStatement(SqlQuery.java:306)